name: movie_app
description: Movie app - Firebase + TMDB (Movie only)
publish_to: none
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Enable Material Icons font
  # (requires uses-material-design: true in flutter section below)
  provider: ^6.0.6
  http: ^0.13.6
  firebase_core: ^2.13.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.3.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  file_picker: ^6.0.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Example of adding fallback fonts if Material Icons fail to load (optional)
  # assets:
  #   - assets/fonts/
